name: Ubuntu Keepalive (max)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: read
  actions: write

concurrency:
  group: ubuntu-keepalive
  cancel-in-progress: false

jobs:
  keepalive:
    name: Runner Ubuntu hidup semaksimal mungkin
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Info OS
        run: |
          uname -a
          cat /etc/os-release
          date -u +"Start at: %Y-%m-%d %H:%M:%S UTC"

      - name: Keep alive ~355 menit (heartbeat tiap 60 detik)
        env:
          TOTAL_MINUTES: "355"
        run: |
          mins=0
          while [ "$mins" -lt "$TOTAL_MINUTES" ]; do
            printf "[Heartbeat] %s - menit ke-%s\n" "$(date -u +"%F %T UTC")" "$mins"
            sleep 60
            mins=$((mins+1))
          done

      - name: Self-dispatch run berikutnya (chain)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_FULL: ${{ github.repository }}
          REF: ${{ github.ref_name }}
          WORKFLOW_FILE: "main.yml"
        run: |
          echo "Memicu run berikutnya di ${REPO_FULL} (ref: ${REF})"
          printf '{ "ref": "%s" }\n' "${REF}" > payload.json
          curl -sS -X POST \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO_FULL}/actions/workflows/${WORKFLOW_FILE}/dispatches" \
            --data @payload.json
          echo "Selesai memicu workflow selanjutnya."
